store/urls.py
"""Defines URL patterns for store."""

from django.urls import path, include

from . import views

app_name = 'store'

urlpatterns = [
    # Home page
    path('', views.products, name = 'products'),
    # New use registration page.
    path('users/register', views.register, name ='register'),
    # Individual product's page.
    path('<int:pro_id>', views.product, name= 'product'),
    # Product Name By Search Page
    path('store/search/',views.searchByProductName,name='searchByProductName'),
    # Confirm and place order 
    path('store/confirm/<int:pro_id>', views.confirm, name='confirm'),
    # Category Wise Show
    path('store/categorywise/',views.categorywise,name='categorywise'),
    #afterOrderRedirectPage
    path('store/afterOrderRedirect',views.afterOrderRedirect,name='afterOrderRedirect'),
]

users/urls.py
"""Urls for users app"""

from django.urls import path, include

from .import views
app_name = "users"

urlpatterns = [
    # Include default auth urls.
    path('users/', include('django.contrib.auth.urls')),
    # Url for redirect page.
    path('users/', views.redirects, name = 'redirects'),
    # Let user see his details
    path('users/details', views.details, name = 'details'),
]

templates/base.html
<!doctype html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no ">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>
        {% block title %} {% endblock %}
    </title>
    <style>
        .col-md-3 {
            display: inline-block;
            margin-left: -4px;
        }
        
        .carousel-indicators .active {
            background-color: blue;
        }
        
        .col-md-3 img {
            max-width: 227px;
            height: 242px;
        }
        
        body .carousel-indicator li {
            background-color: blue;
        }
        
        body .carousel-indicators {
            bottom: 0;
        }
        
        body .carousel-control-prev-icon,
        body .carousel-control-next-icon {
            background-color: blue;
        }
        
        .carousel-control-prev,
        .carousel-control-next {
            top: auto;
            bottom: auto;
            padding-top: 222px;
        }
        
        body .no-padding {
            padding-left: 0;
            padding-right: 0;
        }
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'store:products' %}">Web-Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'store:products' %}">Home</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'users:details' %}">Hello, {{user.username}}</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Supplier Login</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'supplier:register' %}">Supplier Registration</a></li>
                    <li class="nav-item"><a class="nav-link active" class="nav-link active" aria-current="page" href="{% url 'users:login' %}">User login</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'store:register' %}">User Registration</a></li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'supplier:products' %}">Sell your products</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'store:categorywise' %}">Categorywise</a></li>
                </ul>
                <form class="d-flex" action="/store/search" method="GET">
                    {% csrf_token %}
                    <input class="form-control me-2" id="searchquery" name='searchquery' type="search" placeholder="Search Product Name" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div style="margin: 32px;">
        {%block body%} {%endblock%}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!---->
</body>

</html>